### ISSUE TITLE
Migrate the node docker builds to multistage 

### ISSUE THREAD

**Issue by oserban** [ove/ove-install#11]
People should have only docker and docker-compose installed to build this stuff

**Comment by jamesscottbrown** [comment]
Not that once this is done we will need to make some minor changes to the installation instructions.

**Comment by senakafdo** [comment]
The proposed resolution only becomes meaningful if the build will not depend on many `node_modules` and if something such as a webpack configuration can be put together to bundle the logic into a single JS file, for instance. To achieve this, the code needs to migrate to ES6+ standards and use imports etc as webpack does not understand express routes etc. Therefore, in order to fix this issue in a meaningful way, ove/ove-apps#26 and similar fixes to core/services need to be made.

**Comment by oserban** [comment]
Since the rewrite will be a bit more consistent in all the services, we can close this
